# Generated by Django 2.2.5 on 2019-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_auto_20191012_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='https://google.co.in', max_length=500),
            preserve_default=False,
        ),
    ]
