# Generated by Django 2.2.5 on 2019-10-29 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0007_brandcluster_colorcluster_designcluster_productcluster_userscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
