# Generated by Django 2.2.5 on 2019-11-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_auto_20191106_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_design', to='userapi.Designs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='primary_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_color_primary', to='userapi.Colors'),
            preserve_default=False,
        ),
    ]
