# Generated by Django 2.2.5 on 2019-11-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0011_auto_20191111_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
