# Generated by Django 2.2.5 on 2019-11-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0013_auto_20191112_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='userapi.Category'),
        ),
    ]
