# Generated by Django 2.2.5 on 2019-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0014_auto_20191112_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_brands', to='userapi.Category'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_color', to='userapi.Category'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_design', to='userapi.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='userapi.Category'),
        ),
        migrations.AlterField(
            model_name='product_attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute', to='userapi.Category'),
        ),
    ]
