# Generated by Django 2.2.5 on 2019-11-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0015_auto_20191112_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_size',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_size', to='userapi.Category'),
        ),
    ]
