# Generated by Django 2.2.5 on 2019-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0020_auto_20191129_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attribute',
            name='attribute_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_attribute',
            name='attribute_value',
            field=models.CharField(max_length=50),
        ),
    ]
