# Generated by Django 2.2.5 on 2019-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0022_auto_20191129_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='style_tip',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image_url',
            field=models.CharField(max_length=2000),
        ),
    ]
