# Generated by Django 2.2.5 on 2019-12-04 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0023_auto_20191130_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_feedback', to='userapi.Category'),
            preserve_default=False,
        ),
    ]
